### ISSUE TITLE
Assign root.seq

### ISSUE THREAD

**Issue by elewitus** [bsipos/phylosim#1]
Hello,

Is there a way to assign (rather than build) a root.seq?

For example, 

`Simulate(PhyloSim(root.seq=my_fasta_seq,phylo=tree))$alignment`

where my_fasta_seq is an existing protein sequence?

Thanks for any help.

**Comment by bsipos** [comment]
You can always construct a sequence object with specified amino acids and use it as a root sequence. However, the simulation would be strictly speaking flawed, unless the amino acid frequencies match the equilibrium distribution of the substitution model used.

Botond
